### ISSUE TITLE
NT Santa Tracker

### ISSUE THREAD

**Issue by malawrence1020** [NuttyTrains/NuttyTrains.github.io#22]
Phase 1: Complete
Phase 2: Complete
Phase 3: Do some maths first and stop procrastinating!

**Comment by malawrence1020** [comment]
Phase 3: Wow, this is complete too!
Phase 4: Need lots and lots of places from around the UK and around the world. Finally, 5 year old Matthew will get his revenge!

**Comment by malawrence1020** [comment]
Phase 4a: 2nd round of places - complete
Phase 4b: Improved styling - complete
Phase 4c: Music - complete
Phase 4d: Pre-tracker - started
Phase 4e: Final list of places - TBD

**Comment by malawrence1020** [comment]
This is broken again

**Comment by jamesa9283** [comment]
Santa tracker 2023?

**Comment by malawrence1020** [comment]
_Reasonable, reasonable_

**Comment by malawrence1020** [comment]
Closing this for now, because this has apparently worked for the last 3 years without fail, and I think it is best to not touch it in case it explodes
