### ISSUE TITLE
Chinglish Translations

### ISSUE THREAD

**Issue by jamesa9283** [NuttyTrains/NuttyTrains.github.io#7]
"A Chinese version for all our friends from the Hundred acre wood/re-education camp XD"

**Comment by malawrence1020** [comment]
不好猫

**Comment by malawrence1020** [comment]
I have moved this to the project board, as this isn't an issue now

**Comment by malawrence1020** [comment]
It would be funny to reopen this after all this time - the project board I folded this into no longer exists, you have done an entire year of Chinese, and yet neither of us have touched this for almost 2 years. We are good at ticking things off

**Comment by malawrence1020** [comment]
You know, I don't think we thought this one through. Maybe this looked funny when we were underworked first years with only 150 stations to translate (and barely any new stations ever), but we are now on over 500 and are entering fourth year - this is not going to happen xD

**Comment by malawrence1020** [comment]
This is a mercy killing - goodbye failed experiment
